config:
    # choose tf or torch
    FRAMEWORK: torch
    # net
    NET: "MLPNet"
    # model
    MODEL: "MLPModel"
    # gpu
    GPU: 0
    # hidden layers
    HIDDEN_LAYERS: [784, 1000, 1000, 500, 200, 10]
    # hidden layer's activation
    HIDDEN_ACTIVATION: "relu"
    # train dataset
    TRAIN_DATASET: "MNIST"
    # dataset augmentations
    TRAIN_DATASET_AUG: []
    # summary freq
    TRAIN_SUMMARY_FREQ: 10
    # validation freq
    TRAIN_VAL_FREQ: 200
    # save checkpoint model frequency
    TRAIN_SAVE_MODEL_FREQ: 5000
    # start saving best val models after x epochs
    TRAIN_START_SAVING_AFTER_EPOCH: 1
    # train batch size
    TRAIN_BATCH_SIZE: 20
    # number of epochs
    TRAIN_NUM_EPOCHS: 5
    # restore from wandb or local
    TRAIN_RESTORE_STORAGE: "local"
    # path to checkpoint from which to be restored
    TRAIN_RESTORE_FILE: ""
    # learning rate
    TRAIN_LR: 0.0001
    # l1 regularization parameter
    TRAIN_L1: 0
    # upload best model weights to wandb
    UPLOAD_BEST_TO_WANDB: false
    # validation batch size
    VAL_BATCH_SIZE: 20
    # test batch size
    TEST_BATCH_SIZE: 20
    # path to checkpoint from which to be restored
    TEST_RESTORE_FILE: ""
    # restore from wandb or local
    TEST_RESTORE_STORAGE: ""
    # dataset for testing
    TEST_DATASET: "MNIST"
    # dataset augmentations
    TEST_DATASET_AUG: []
