config:
  # model name
  model: "vpg"
  # environment
  env: "CartPole-v0"
  # total number of iterations
  num_iterations: 100
  # mlp architecture (only hidden layers are specified)
  arch: ["64", "64"]
  # mlp hidden layer activation
  activation: "tanh"
  # learning rate
  lr: 0.005
  # batch size
  batch_size: 1000
  # discount gamma
  gamma: 1.0
  # use reward to go
  reward_to_go: true
  # use baselines
  baselines: true
